# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccpool-beta" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "806e351a63054c9e387b99b1c20124b3ac2bc66aeb3a9226398098cf61476f6d"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc854617ec41e45889e2243780bbe09193c65c479b36be1ef7ea6b29184be850"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbee0d337be1aa6a89f78dff5753c91920d77d977d022010fcb0bde7cde2e615"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "79bd716ed2b42a20bc270f1860ab6848a4123865354a5510ea0b716fd9c575cf"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccpool-beta"
  desc "Get the most out of a fixed Claude subscription pool (bleeding-edge channel)"
  homepage "https://github.com/SeanLF/ccpool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccpool"

  # No zap stanza required

end
