# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccpool-beta" do
  depends_on macos: :ventura

  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "385c7c40b2936286de67fdd1fd5451e10179174b9f3d136fdde8ef73b5455def"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "de9055832d229a2027dcc49f06b7eda8491b0630ef0f2c104d86493d351a42b6"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "81387ec5aed2a74d7f70a1c6a63a41bafbe2becbf1975df599ab8e71548e5ac9"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "801120ff88e08015ff3dba810856fbc6a9432335d7de8dd57a15864fc9820b84"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccpool-beta"
  desc "Get the most out of a fixed Claude subscription pool (bleeding-edge channel)"
  homepage "https://github.com/SeanLF/ccpool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccpool"

  # No zap stanza required

  caveats <<~EOS
    Run `ccpool init` to wire the statusline + warn hooks into
    ~/.claude/settings.json. It is idempotent (skips what is already wired);
    re-run after an upgrade to pick up any new hook events.
  EOS
end
