# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccpool-beta" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "22af4da486d178a82df86c5645b6c2deaf8303c135fd0282cdb873da4cae22c0"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ed6153450ba7df9dfb90f2f23397f9a08631ccaad0bbf2376d42f32ccb83a7f"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6debb5f01af58be4158241de9f473914413ab61ae879c51c1de4e265955e4fd7"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7dd92593cbd09a2265ba9729736de3eb175ed310888fb0b587c4652d9bd67351"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccpool-beta"
  desc "Get the most out of a fixed Claude subscription pool (bleeding-edge channel)"
  homepage "https://github.com/SeanLF/ccpool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccpool"

  # No zap stanza required

end
