# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccpool" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "1fdfbf3c1f3c97aadf543558256d0bd5640e4df26161a02d8ba07ab1f2e040f6"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03584563ad8ee47340743c79ba298844d4bc0a19256a070444ab0ec0885a5605"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99744f1b280b438d053823cc4a1f77d1c1f2df3b10b118f519d62a9fb903b396"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1c125ad763b2f8195c2125c667e338afd3f63d60a7ed6540b6edfd12d17e6ed"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccpool"
  desc "Get the most out of a fixed Claude subscription pool"
  homepage "https://github.com/SeanLF/ccpool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccpool"

  # No zap stanza required

  caveats <<~EOS
    Run `ccpool init` to wire the statusline + warn hooks into
    ~/.claude/settings.json. It is idempotent (skips what is already wired);
    re-run after an upgrade to pick up any new hook events.
  EOS
end
