# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccpool" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "c9b8c2f3135424afc4f81ad35981c4ae60df25461189b5443a56adb172505400"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e4f8d89d8482a82f9f7638d3b2240796e91104cff4f808a9c96793b396aa7cc"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "56f6b92246d1ca4e2a2dd1c65c8ce1ace92a2a486f5ae3bab663809e02dc32ca"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b125faa4ae486e2c52228a15f1ec84b9c6dc30a7ee9013228199f62a9cb5d1ec"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccpool"
  desc "Get the most out of a fixed Claude subscription pool"
  homepage "https://github.com/SeanLF/ccpool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccpool"

  # No zap stanza required

end
