# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccpool" do
  depends_on macos: :ventura

  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "4043cf8b34ac83dafe9f36846f0441e7450d59506699ce04e35cecfd1ca2b2e4"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3075a6f0318e6c234c9f59c3ed67c28e76d1053b603cfc921d6c3ff252a2794a"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "86cb57bcd4d678a765dd710a41b8e1010e845a292e2f5d9d2522941bd18578ad"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "80b56803d66b7709f6701c044f79876ae4f05091c92daad3c17429dffc3d2169"
      url "https://github.com/SeanLF/ccpool/releases/download/v#{version}/ccpool_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccpool"
  desc "Get the most out of a fixed Claude subscription pool"
  homepage "https://github.com/SeanLF/ccpool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccpool"

  # No zap stanza required

  caveats <<~EOS
    Run `ccpool init` to wire the statusline + warn hooks into
    ~/.claude/settings.json. It is idempotent (skips what is already wired);
    re-run after an upgrade to pick up any new hook events.
  EOS
end
